repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort app main.py
        language: system
        types: [python]
        args: ["--profile", "black"]
        pass_filenames: false

      - id: black
        name: black
        entry: poetry run black app main.py
        language: system
        types: [python]
        args: ["--line-length", "80"]
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
