services:
    backend:
        image: fastapi
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        environment:
            - JWT_SECRET=${JWT_SECRET}
            - JWT_ALGORITHM=${JWT_ALGORITHM:-HS256}
            - JWT_EXPIRE_MINUTES=${JWT_EXPIRE_MINUTES:-60}
            - SQLALCHEMY_DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
            - WAIT_HOSTS=db:5432
            - REDIS_URL=redis://default:${REDIS_PASSWORD}@redis:6379/0
        depends_on:
            - db
            - redis
    db:
        image: postgres:15.3
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - "5432:5432"

    redis:
        image: redis:latest
        command: redis-server --requirepass ${REDIS_PASSWORD}
        ports:
            - '6379:6379'
        restart: unless-stopped
        volumes:
            - redis_data:/data
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}

volumes:
    redis_data:
